language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-leaflet' ]; then cd .. && eval "mv $currentfolder generator-leaflet" && cd generator-leaflet; fi

